src/meals/urls.py
from django.urls import path
from . import views

app_name = 'meals'

urlpatterns = [
    path('',views.meal_list , name='meal_list'),
    path('<slug:slug>' , views.meal_detail , name='meal_detail'),
]

src/myhotel/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls' , namespace='meals')),
    path('reserve_table/', include('reservation.urls' , namespace='reservation')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/reservation/urls.py
from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('',views.reserve_table , name='reserve_table'),
]

src/meals/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Meals(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    category = models.ForeignKey('Category', on_delete= models.SET_NULL, null=True)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    preperation_time = models.IntegerField()
    image = models.ImageField(upload_to='meals/')
    slug = models.SlugField(blank=True, null=False)

    def save(self , *args , **kwargs):
        if not self.slug and self.name :
            self.slug = slugify(self.name)
        super(Meals , self).save(*args , **kwargs)

    class Meta:
        verbose_name = 'meal'
        verbose_name_plural = 'meals'

    def __str__ (self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    

src/reservation/models.py
from django.db import models

# Create your models here.
class Reservation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()
    number_of_person = models.IntegerField()
    Date = models.DateField()
    time = models.TimeField()


    def __str__(self):
        return self.name
    

src/reservation/forms.py
from django import forms
from .models import Reservation


class ReserveTableForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'

src/meals/views.py
from django.shortcuts import render

# Create your views here.
from .models import Meals , Category

def meal_list(request):
    meal_list = Meals.objects.all()
    categories = Category.objects.all()

    context = {
        'meal_list' : meal_list ,
        'categories' : categories ,    
    }

    return render(request , 'Meals/list.html' , context)

def meal_detail(request , slug):

    meal_detail = Meals.objects.get(slug=slug)

    context = {'meal_detail' : meal_detail,}

    return render(request , 'Meals/detail.html' , context)

src/reservation/views.py
from .models import Reservation
from django.shortcuts import render
from .forms import ReserveTableForm

from reservation.models import Reservation
# Create your views here.

def reserve_table(request):
    reserve_form = ReserveTableForm()

    if request.method == 'POST' :
        reserve_form = ReserveTableForm(request.POST)

        if reserve_form.is_valid():
            reserve_form.save()

    context = {'form' : reserve_form}

    return render(request,'Reservation/reservation.html', context)

src/meals/templates/Meals/detail.html
{% extends 'base.html'%}
{% load static %}
{% block body %}

<div class="main-wrap">
<div class="cover_1">
    <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row align-items-center">
        <div class="col-md-12" data-aos="fade-up">
            <h2 class="heading">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit ipsa sint amet aliquam velit minima tenetur quisquam beatae molestiae possimus dicta.</h2>
        </div>
        </div>
    </div>
    </div>
</div> <!-- .cover_1 -->

{% comment %}
<div class="section">
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-7 text-center"  data-aos="fade-up">
        <h2 class="mb-4">Our Specialties</h2>
        <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae eum voluptatem odio expedita laborum fugit repudiandae dolorem consectetur.</p>
        </div>
    </div>
    </div>
</div> <!-- .section -->

<div class="section pt-0 pb-0">

    <div class="menus d-flex bg-light">
    <div class="d-flex item">
        <div class="image" style="background-image: url(img/img_1.jpg);" data-aos="fade"></div>
        <div class="text">
        <h3>Grilled Egg With Garlic</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
        <p class="price">$5.00</p>
        </div>
    </div> <!-- .item -->

    <div class="d-flex item">
        <div class="image order-2 order-md-1"  style="background-image: url(img/img_2.jpg);" data-aos="fade" data-aos-delay="100"></div>
        <div class="text order-1 order-md-2">
        <h3>Organic Tomato Salad</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
        <p class="price">$6.00</p>
        </div>
    </div> <!-- .item -->

    <div class="d-flex item">
        <div class="image order-1 order-md-2 order-lg-2 order-xl-1" style="background-image: url(img/img_3.jpg);" data-aos="fade" data-aos-delay="200"></div>
        <div class="text order-2 order-md-1 order-lg-1 order-xl-2">
        <h3>Flatbread</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
        <p class="price">$9.00</p>
        
        </div>
    </div> <!-- .item -->

    <div class="d-flex item">
        <div class="image order-2" style="background-image: url(img/img_4.jpg);" data-aos="fade" data-aos-delay="300"></div>
        <div class="text order-1 mb-3">
        <h3>Rack Of Lamb</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
        <p class="price">$13.00</p>
        </div>
    </div> <!-- .item -->

    <div class="d-flex item">
        <div class="image order-1 order-lg-1 order-xl-2" style="background-image: url(img/img_5.jpg);" data-aos="fade" data-aos-delay="400"></div>
        <div class="text order-2 order-lg-2 order-xl-1">
        <h3>Eggplant Parmigiana</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
        <p class="price">$9.00</p>
        </div>
    </div> <!-- .item -->

    <div class="d-flex item">
        <div class="image order-2 order-md-1 order-lg-1 order-xl-2" style="background-image: url(img/img_6.jpg);" data-aos="fade" data-aos-delay="500"></div>
        <div class="text order-1 order-md-2 order-lg-2 order-xl-1">
        <h3>Spicy Meatballs</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
        <p class="price">$7.00</p>
        </div>
    </div> <!-- .item -->

    </div>
</div>

{% endcomment %}

<div class="section">
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8" data-aos="fade-up">

            <img src="{{meal_detail.image.url}}" alt="" width="720" height="500">
            <h2>{{meal_detail}}</h2>
            <p>{{meal_detail.description}}</p>

            <p>For: {{meal_detail.people}} People</p>
            <p>Preperation Time: {{meal_detail.preperation_time}} Minutes</p>
            <p>Price: {{meal_detail.price}}$</p>

        </div>
    </div>
    </div>
</div>



</div> <!-- .main-wrap -->

{% endblock body %}

src/meals/templates/Meals/list.html
{% extends 'base.html'%}
{% load static %}
{% block body %}

      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit ipsa sint amet aliquam velit minima tenetur quisquam beatae molestiae possimus dicta.</h2>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

        {% comment %}
        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-7 text-center"  data-aos="fade-up">
                <h2 class="mb-4">Our Specialties</h2>
                <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae eum voluptatem odio expedita laborum fugit repudiandae dolorem consectetur.</p>
              </div>
            </div>
          </div>
        </div> <!-- .section -->
        
        <div class="section pt-0 pb-0">

          <div class="menus d-flex bg-light">
            <div class="d-flex item">
              <div class="image" style="background-image: url(img/img_1.jpg);" data-aos="fade"></div>
              <div class="text">
                <h3>Grilled Egg With Garlic</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$5.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-2 order-md-1"  style="background-image: url(img/img_2.jpg);" data-aos="fade" data-aos-delay="100"></div>
              <div class="text order-1 order-md-2">
                <h3>Organic Tomato Salad</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$6.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-1 order-md-2 order-lg-2 order-xl-1" style="background-image: url(img/img_3.jpg);" data-aos="fade" data-aos-delay="200"></div>
              <div class="text order-2 order-md-1 order-lg-1 order-xl-2">
                <h3>Flatbread</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$9.00</p>
                
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-2" style="background-image: url(img/img_4.jpg);" data-aos="fade" data-aos-delay="300"></div>
              <div class="text order-1 mb-3">
                <h3>Rack Of Lamb</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$13.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-1 order-lg-1 order-xl-2" style="background-image: url(img/img_5.jpg);" data-aos="fade" data-aos-delay="400"></div>
              <div class="text order-2 order-lg-2 order-xl-1">
                <h3>Eggplant Parmigiana</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$9.00</p>
              </div>
            </div> <!-- .item -->

            <div class="d-flex item">
              <div class="image order-2 order-md-1 order-lg-1 order-xl-2" style="background-image: url(img/img_6.jpg);" data-aos="fade" data-aos-delay="500"></div>
              <div class="text order-1 order-md-2 order-lg-2 order-xl-1">
                <h3>Spicy Meatballs</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo quisquam saepe quaerat.</p>
                <p class="price">$7.00</p>
              </div>
            </div> <!-- .item -->

          </div>
        </div>

        {% endcomment %}

        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-8" data-aos="fade-up">

                <h2 class="mb-5 text-center">Menu List with Price</h2>

                <ul class="nav site-tab-nav" id="pills-tab" role="tablist">
                  {% for category in categories %}
                    <li class="nav-item">
                      <a class="nav-link" id="{{category}}-tab" data-toggle="pill" href="#{{category}}" role="tab" aria-controls="{{category}}" aria-selected="true">{{category}}</a>
                    </li>
                  {% endfor %}
                </ul>


                <div class="tab-content" id="pills-tabContent">

                  {% for category in categories %}


                    <div class="tab-pane fade show" id="{{category}}" role="tabpanel" aria-labelledby="{{category}}-tab">

                      {% for meal in meal_list %}
                        {% if meal.category == category %}
                          <div class="d-block d-md-flex menu-food-item">
                            <div class="text order-1 mb-3">
                              <h3><a href={%url 'meals:meal_detail' meal.slug %}>{{meal.name}}</a></h3>
                              <p>{{meal.description}}</p>
                            </div>
                            <div class="price order-2">
                              <strong>{{meal.price}}</strong>
                            </div>
                          </div> <!-- .menu-food-item -->
                          {% endif %}
                      {% endfor %}



                    </div>
                  {% endfor %}
                </div>


              </div>
            </div>
          </div>
        </div>

        

      </div> <!-- .main-wrap -->
      
      {% endblock body %}

src/reservation/templates/Reservation/reservation.html
{% extends 'base.html' %}    
{% load static%}
{% block body %}
      <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7" data-aos="fade-up">
                  <h2 class="heading">Reservation</h2>
                  <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo saepe dolorum dolorem, iste officia voluptates! Sint repudiandae, soluta voluptatem delectus iure, eaque, harum expedita, nisi aliquam magni odio perferendis ipsum!</p>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->
        
        <div class="section" data-aos="fade-up">
          <div class="container">
            <div class="row justify-content-center mb-5">
              <div class="col-md-8  text-center">
                <h2 class="mb-3">Reservation</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga, alias distinctio voluptatum magni voluptatibus.</p>
              </div>
            </div>
            <div class="row justify-content-center">
              <div class="col-md-10 p-5 form-wrap">
                
                {% comment %}
                <form action="#">
                  <div class="row mb-4">
                    <div class="form-group col-md-4">
                      <label for="name" class="label">Name</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-person"></span>
                        <input type="text" class="form-control" id="name">
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="email" class="label">Email</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-email"></span>
                        <input type="email" class="form-control" id="email">
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="phone" class="label">Phone</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-call"></span>
                        <input type="text" class="form-control" id="phone">
                      </div>
                    </div>

                    <div class="form-group col-md-4">
                      <label for="persons" class="label">Number of Persons</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-arrow-dropdown"></span>
                        <select name="persons" id="persons" class="form-control">
                          <option value="">1 person</option>
                          <option value="">2 persons</option>
                          <option value="">3 persons</option>
                          <option value="">4 persons</option>
                          <option value="">5+ persons</option>
                        </select>
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="date" class="label">Date</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-calendar"></span>
                        <input type="text" class="form-control" id="date">
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="time" class="label">Time</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-time"></span>
                        <input type="text" class="form-control" id="time">
                      </div>
                    </div>
                  </div>
                  <div class="row justify-content-center">
                    <div class="col-md-4">
                      <input type="submit" class="btn btn-primary btn-outline-primary btn-block" value="Submit">
                      <!-- <p><a href="#" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p> -->
                    </div>
                  </div>
                </form>
                {% endcomment %}
<!-- Form -->
                <form action="" method="POST">
                  {% csrf_token %}
                  {{form}}
                  <button type="submit"class="btn-primary ">Submit</button>
                </form>

              </div>
            </div>
          </div>
        </div> <!-- .section -->

        <!-- <div class="map-wrap" id="map"  data-aos="fade"></div>

        <div class="section" data-aos="fade">
          <div class="container">
            <div class="row justify-content-center mb-5">
              <div class="col-md-7 text-center"  data-aos="fade-up">
                <h2 class="mb-4">Customer's Reviews</h2>
              </div>
            </div>
            <div class="row justify-content-center text-center" data-aos="fade-up">
              <div class="col-md-8">
                <div class="owl-carousel home-slider-loop-false">

                
                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quaerat recusandae molestias incidunt sapiente sit numquam delectus mollitia! Non laudantium impedit voluptas consequatur corrupti. Cumque consequuntur nemo eos et error!&rdquo;</p>
                      <div class="author">
                        <img src="img/person_1.jpg" alt="Image placeholder" class="mb-3">
                        <h4>Maxim Smith</h4>
                        <p>CEO, Founder</p>
                      </div>
                    </blockquote>
                  </div>
                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Sint adipisci laborum dolorum ipsa quidem alias ipsum aperiam aut! Quis rerum soluta dolorem iure nihil velit error sequi? Dignissimos accusantium adipisci unde officia? Dolores aut sequi dolorum repellendus quod.&rdquo;</p>
                      <div class="author">
                        <img src="img/person_2.jpg" alt="Image placeholder" class="mb-3">
                        <h4>Geert Green</h4>
                        <p>CEO, Founder</p>
                      </div>
                    </blockquote>
                  </div>
                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Ratione alias iure ab facere quia aliquam dolor et voluptates esse nihil corporis distinctio hic ea quo ducimus autem cum amet. Quos accusamus iusto porro nulla temporibus numquam commodi soluta.&rdquo;</p>
                      <div class="author">
                        <img src="img/person_3.jpg" alt="Image placeholder" class="mb-3">
                        <h4>Dennis Roman</h4>
                        <p>CEO, Founder</p>
                      </div>
                    </blockquote>
                  </div>
                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Ad quod aspernatur ipsa. Numquam expedita delectus qui ad explicabo voluptas eos vel reiciendis magnam rerum quaerat quisquam accusantium quae saepe ipsam ullam ut ea molestiae porro. Recusandae veniam maxime.&rdquo;</p>
                      <div class="author">
                        <img src="img/person_2.jpg" alt="Image placeholder" class="mb-3">
                        <h4>Geert Green</h4>
                        <p>CEO, Founder</p>
                      </div>
                    </blockquote>
                  </div>
                </div>
              </div>
            </div>
          </div>  
        </div> .section -->

  

      </div> <!-- .main-wrap -->
{% endblock body %}

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>Colorlib Diner</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:300,400,700,800|Open+Sans:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'site_static/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/animate.css' %}">
    <link rel="stylesheet" href="css/owl.carousel.min.css">

    <link rel="stylesheet" href="{% static 'site_static/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/css/bootstrap-datepicker.css' %}>
    <link rel="stylesheet" href="{% static 'site_static/css/jquery.timepicker.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/fonts/fontawesome/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/fonts/flaticon/font/flaticon.css' %}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'site_static/css/style.css' %}">
  </head>
  <body>
    

    <div class="site-wrap">
      
      <nav class="site-menu">
        <div class="site-menu-inner">
          <ul class="list-unstyled">
            <li class="active"><a href="index.html">Home</a></li>
            <li><a href="about.html">About Us</a></li>
            <li><a href="menu.html">Our Menu</a></li>
            <li><a href="blog.html">Our Blog</a></li>
            <li><a href="{% url 'reservation:reserve_table' %}">Reserve A Table</a></li>
            <li><a href="contact.html">Contact</a></li>
          </ul>
        </div>
      </nav>

      <header class="site-header">
        <div class="row align-items-center">
          <div class="col-5 col-md-3">
             <ul class="list-unstyled social">
              <li><a href="#"><span class="fa fa-facebook"></span></a></li>
              <li><a href="#"><span class="fa fa-twitter"></span></a></li>
              <li><a href="#"><span class="fa fa-instagram"></span></a></li>
            </ul>
          </div>
          <div class="col-2 col-md-6 text-center">
            <a href="index.html" class="site-logo">D</a>
          </div>
          <div class="col-5 col-md-3 text-right menu-burger-wrap">
            <a href="#" class="site-nav-toggle js-site-nav-toggle"><i></i></a>

          </div>
        </div>
       
      </header> <!-- site-header -->
      
      {% block body %}

      {% endblock body%}
      

      <footer>
        <div class="site-footer">
          <div class="container">
            <div class="row small-gutters mb-5">
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="100">
                <div class="footer-widget">
                  <h3>Diner Restaurant</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel neque, odio illum. Est minima sint minus sunt ducimus.</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="200">
                <div class="footer-widget">
                  <h3>Lunch Service</h3>
                  <p>Booking from 12:00pm - 1:30pm</p>
                  <h3>Dinner Service</h3>
                  <p>Everyday: <br> Booking from 6:00pm - 9:00pm</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="300">
                <div class="footer-widget">
                  <h3>Quick Links</h3>
                  <ul>
                    <li><a href="#">Help &amp; Support</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Get in Touch</a></li>
                    <li><a href="#">Testimonials</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="400">
                <div class="footer-widget footer-contact-widget">

                  <h3>Subscribe</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                  <form action="" class="form-subscribe mb-5">
                    <div class="form-group form-field">
                      <input type="submit" value="Send" class="btn btn-primary">
                      <input type="text" class="form-control" placeholder="Email">
                    </div>
                  </form>

                  <h3>Contact Us</h3>
                  <p class="contact-email">info@yourdomain.com</p>
                  <p class="contact-phone">1-444-123-9829</p>
                  
                  
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </footer>

      <div class="site-footer-copyright">
        <div class="container">
          <div class="row">

             <p class="footer-text col-md-12"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>

    </div>

    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'site_static/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'site_static/js/popper.min.js' %}"></script>
    <script src="{% static 'site_static/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site_static/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.waypoints.min.js' %}"></script>

    <script src="{% static 'site_static/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.timepicker.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.stellar.min.js' %}"></script>

    <script src="{% static 'site_static/js/aos.js' %}"></script>
    

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>

    <script src="{% static 'site_static/js/main.js' %}"></script>
  </body>
</html>